sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
before_script:
  - npm install
script:
  - npm run-script lint
before_deploy:
  - npm run build
  - zip -r $TRAVIS_BUILD_NUMBER.zip dist/*
  - git tag $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_NUMBER.zip
  skip_cleanup: true
  draft: true
  on:
    branch: master

